# Generated by Django 5.1.8 on 2025-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coin_balance",
            field=models.IntegerField(default=1000),
        ),
    ]
